pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out FSD project...'
                checkout scm
            }
        }

        stage('Environment Check') {
            steps {
                bat 'node --version'
                bat 'npm --version'
            }
        }

        stage('Backend Install') {
            steps {
                dir('backend') {
                    bat 'npm install'
                }
            }
        }

        stage('Frontend Install') {
            steps {
                dir('frontend') {
                    bat 'npm install'
                }
            }
        }

        stage('Frontend Build') {
            steps {
                dir('frontend') {
                    bat 'npm run build'
                }
            }
        }

        stage('Generate Feedback') {
            steps {
                script {

                    def feedback = """
========================================
        FSD PROJECT CI/CD FEEDBACK
========================================

Project:
College ODS Full Stack Project

Jenkins Build Number:
${env.BUILD_NUMBER}

Git Branch:
${env.BRANCH_NAME ?: 'main'}

Build URL:
${env.BUILD_URL}

----------------------------------------
PIPELINE STAGES
----------------------------------------

✓ GitHub Repository Checkout
✓ Node.js Environment Check
✓ Backend npm install
✓ Frontend npm install
✓ Frontend Production Build

----------------------------------------
OVERALL STATUS
----------------------------------------

BUILD COMPLETED SUCCESSFULLY

========================================
Generated by Jenkins
========================================
"""

                    writeFile(
                        file: 'feedback.txt',
                        text: feedback
                    )

                    echo 'feedback.txt generated successfully.'
                }
            }
        }

        stage('Check Feedback') {
            steps {
                bat 'dir'
                bat 'type feedback.txt'
            }
        }

        stage('Push Feedback to GitHub') {
            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'github-push',
                        usernameVariable: 'GIT_USERNAME',
                        passwordVariable: 'GIT_TOKEN'
                    )
                ]) {

                    bat '''
                        git config user.name "Jenkins"
                        git config user.email "jenkins@localhost"

                        git add feedback.txt

                        git diff --cached --quiet || git commit -m "Add Jenkins feedback [skip ci]"

                        git push https://%GIT_USERNAME%:%GIT_TOKEN%@github.com/Coder-Yashika/FSD_Project.git HEAD:main
                    '''
                }
            }
        }
    }

    post {

        always {

            archiveArtifacts(
                artifacts: 'feedback.txt',
                allowEmptyArchive: true
            )

            echo 'Feedback file processing completed.'
        }

        success {
            echo '===================================='
            echo 'FSD PIPELINE SUCCESSFUL'
            echo '===================================='
        }

        failure {
            echo '===================================='
            echo 'FSD PIPELINE FAILED'
            echo '===================================='
        }
    }
}