pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out FSD project...'
                checkout scm
            }
        }

        stage('Environment Check') {
            steps {
                bat 'node --version'
                bat 'npm --version'
            }
        }

        stage('Backend Install') {
            steps {
                dir('backend') {
                    bat 'npm install'
                }
            }
        }

        stage('Frontend Install') {
            steps {
                dir('frontend') {
                    bat 'npm install'
                }
            }
        }

        stage('Frontend Build') {
            steps {
                dir('frontend') {
                    bat 'npm run build'
                }
            }
        }

        stage('Generate Feedback') {
            steps {
                script {

                    def feedback = """
========================================
        FSD PROJECT CI/CD FEEDBACK
========================================

Project:
College ODS Full Stack Project

Jenkins Build Number:
${env.BUILD_NUMBER}

Git Branch:
${env.BRANCH_NAME ?: 'main'}

Build URL:
${env.BUILD_URL}

----------------------------------------
PIPELINE STAGES
----------------------------------------

✓ GitHub Repository Checkout
✓ Node.js Environment Check
✓ Backend npm install
✓ Frontend npm install
✓ Frontend Production Build

----------------------------------------
OVERALL STATUS
----------------------------------------

BUILD COMPLETED

========================================
Generated by Jenkins
========================================
"""

                    writeFile(
                        file: 'feedback.txt',
                        text: feedback
                    )

                    echo 'feedback.txt generated successfully.'
                }
            }
        }
    }

    post {

        always {

            archiveArtifacts(
                artifacts: 'feedback.txt',
                allowEmptyArchive: true
            )

            echo 'Feedback file processing completed.'
        }

        success {
            echo '===================================='
            echo 'FSD PIPELINE SUCCESSFUL'
            echo '===================================='
        }

        failure {
            echo '===================================='
            echo 'FSD PIPELINE FAILED'
            echo '===================================='
        }
    }
}