pipeline {

    agent any

    stages {

        stage('Environment Check') {
            steps {
                bat 'node --version'
                bat 'npm --version'
            }
        }

        stage('Backend Install') {
            steps {
                dir('backend') {
                    bat 'npm install'
                }
            }
        }

        stage('Frontend Install') {
            steps {
                dir('frontend') {
                    bat 'npm install'
                }
            }
        }

        stage('Frontend Build') {
            steps {
                dir('frontend') {
                    bat 'npm run build'
                }
            }
        }

        stage('Generate Feedback') {
            steps {
                script {

                    def repoUrl = bat(
                        script: 'git config --get remote.origin.url',
                        returnStdout: true
                    ).trim()

                    def repoName = repoUrl
                        .replace('https://github.com/', '')
                        .replace('http://github.com/', '')
                        .replace('.git', '')

                    def nodeVersion = bat(
                        script: 'node --version',
                        returnStdout: true
                    ).trim()

                    def npmVersion = bat(
                        script: 'npm --version',
                        returnStdout: true
                    ).trim()

                    def commitId = bat(
                        script: 'git rev-parse --short HEAD',
                        returnStdout: true
                    ).trim()

                    def commitMessage = bat(
                        script: 'git log -1 --pretty=%%B',
                        returnStdout: true
                    ).trim()

                    def buildDate = new Date().format(
                        'dd-MM-yyyy HH:mm:ss'
                    )

                    def feedback = """
========================================
       FSD PROJECT CI/CD FEEDBACK
========================================

Project:
College ODS Full Stack Project

Repository:
${repoName}

Jenkins Build Number:
${env.BUILD_NUMBER}

Git Branch:
${env.BRANCH_NAME ?: 'main'}

Git Commit:
${commitId}

Commit Message:
${commitMessage}

Build Date:
${buildDate}

Build URL:
${env.BUILD_URL}

----------------------------------------
ENVIRONMENT
----------------------------------------

Node.js:
${nodeVersion}

npm:
${npmVersion}

----------------------------------------
PIPELINE STAGES
----------------------------------------

✓ GitHub Repository Checkout
✓ Node.js Environment Check
✓ Backend npm install
✓ Frontend npm install
✓ Frontend Production Build
✓ Feedback File Generation

----------------------------------------
OVERALL STATUS
----------------------------------------

BUILD COMPLETED SUCCESSFULLY

----------------------------------------
FEEDBACK
----------------------------------------

Generated automatically by Jenkins CI/CD.

========================================
          Generated by Jenkins
========================================
"""

                    writeFile(
                        file: 'feedback.txt',
                        text: feedback
                    )

                    echo 'feedback.txt generated successfully.'
                }
            }
        }

        stage('Check Feedback') {
            steps {
                bat 'type feedback.txt'
            }
        }

        stage('Push Feedback to GitHub') {
            when {
                expression {
                    def message = bat(
                        script: 'git log -1 --pretty=%%B',
                        returnStdout: true
                    ).trim()

                    return !message.contains('[skip ci]')
                }
            }

            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'github-push',
                        usernameVariable: 'GIT_USERNAME',
                        passwordVariable: 'GIT_TOKEN'
                    )
                ]) {

                    bat '''
                        git config user.name "Jenkins"
                        git config user.email "jenkins@localhost"

                        git add feedback.txt

                        git diff --cached --quiet || git commit -m "Add Jenkins feedback [skip ci]"

                        git push https://%GIT_USERNAME%:%GIT_TOKEN%@github.com/Coder-Yashika/Devops_2026_CS_F_12.git HEAD:main
                    '''
                }
            }
        }
    }

    post {

        always {

            archiveArtifacts(
                artifacts: 'feedback.txt',
                allowEmptyArchive: true
            )

            echo 'Feedback file processing completed.'
        }

        success {
            echo '===================================='
            echo 'FSD PIPELINE SUCCESSFUL'
            echo '===================================='
        }

        failure {
            echo '===================================='
            echo 'FSD PIPELINE FAILED'
            echo '===================================='
        }
    }
}